# .properties -> yaml format (python indented)
# spring.main.banner-mode=off
# spring.main.log-startup-info=false
# ...

spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: yollaDB
  main:
    banner-mode: off
    log-startup-info: false
app:
  name: YollaBackend